import React,{useEffect,useRef,useState} from 'react';
import {startGaiaGlobe} from './globe';
import './public-viewer.css';
import GaiaLogo from './GaiaLogo';
type Manifest={generated_utc:string;images:{at:string}[];credits:{name:string;website?:string;acknowledgement:string;copyright:string}[]};
export default function PublicViewer(){
  const canvas=useRef<HTMLCanvasElement>(null),epoch=useRef(Date.now()),loading=useRef(false);
  const [manifest,setManifest]=useState<Manifest>(),[index,setIndex]=useState(-1),[play,setPlay]=useState(false),[credits,setCredits]=useState(false),[error,setError]=useState('');
  useEffect(()=>{const controller=new AbortController();const refresh=()=>fetch('/gaia/public/manifest.json',{cache:'no-store',signal:controller.signal}).then(r=>{if(!r.ok)throw Error('Published images unavailable');return r.json()}).then(m=>{setManifest(m);setError('')}).catch(e=>{if(!controller.signal.aborted)setError(String(e.message))});void refresh();const timer=setInterval(refresh,60000);return()=>{controller.abort();clearInterval(timer)}},[]);
  useEffect(()=>canvas.current?startGaiaGlobe(canvas.current,()=>epoch.current,b=>{loading.current=b},true):undefined,[]);
  useEffect(()=>{if(manifest?.images.length)epoch.current=Date.parse(manifest.images[index<0?manifest.images.length-1:Math.min(index,manifest.images.length-1)].at)},[manifest,index]);
  useEffect(()=>{if(!play||!manifest?.images.length)return;const timer=setInterval(()=>{if(!loading.current)setIndex(i=>(i+1)%manifest.images.length)},250);return()=>clearInterval(timer)},[play,manifest]);
  const frames=manifest?.images||[],at=frames[index<0?frames.length-1:Math.min(index,frames.length-1)]?.at;
  return <main className="gaia-public">
    <header className="public-header"><div className="public-brand"><GaiaLogo/><div><h1>GAIA <span>Data Center</span></h1><p>Global Auroral Image Archive</p></div></div><a className="public-uit" href="https://uit.no/" target="_blank" rel="noreferrer"><img src="/gaia/uit-logo-white.png" alt="UiT The Arctic University of Norway"/></a><button aria-expanded={credits} onClick={()=>setCredits(!credits)}>ⓘ <span>Info &amp; credits</span></button></header>
    <div className="public-globe"><canvas ref={canvas} aria-label="Interactive auroral globe"/><div className="public-hint">Drag to rotate · Scroll or pinch to zoom</div>
    {credits&&<section className="public-info" role="dialog" aria-label="Information and credits"><div className="public-info-heading"><h2>About GAIA</h2><button onClick={()=>setCredits(false)} aria-label="Close information">✕</button></div><img src="/gaia/uit-logo-white.png" alt="UiT" width={120}/><p>Juha Vierinen · Björn Gustavsson</p><p>Real calibrated camera images, stitched on Revontuli and projected onto a shell 100 km above Earth. The globe shows coastlines, political boundaries, full-IGRF magnetic latitudes and the solar terminator for the selected time.</p><p>Drag to rotate, scroll or pinch to zoom. Play advances through the available composites; Latest returns to the newest published frame. Gaps mean no usable calibrated observations were available.</p><p>Currently showing a rolling 24-hour window, sampled every five minutes plus the latest frame. Full-night and calendar-date playback are planned, not yet available.</p><h2>Data providers &amp; credits</h2><p>Every image retains its producer’s copyright. These are display composites, not synthetic aurora.</p>{manifest?.credits.map((c,i)=><p key={i}><a href={c.website||undefined} target="_blank" rel="noreferrer">{c.name}</a><br/>{c.acknowledgement}<br/>{c.copyright}</p>)}</section>}</div>
    <section className="public-playback" aria-label="Aurora playback"><div className="public-playback-row"><button className="public-play" disabled={!frames.length} onClick={()=>{if(!play&&index<0)setIndex(0);setPlay(!play)}}>{play?'❚❚ Pause':'▶ Play'}</button><button disabled={!frames.length} onClick={()=>{setPlay(false);setIndex(-1)}}>Latest</button><time>{at?new Date(at).toISOString().replace('T',' ').replace('.000Z',' UTC'):'Waiting for publication'}</time></div><input aria-label="Observation time" disabled={!frames.length} type="range" min={0} max={Math.max(0,frames.length-1)} value={index<0?Math.max(0,frames.length-1):Math.min(index,frames.length-1)} onChange={e=>setIndex(Number(e.target.value))}/><div className="public-timeline-labels"><span>{frames.length?new Date(frames[0].at).toISOString().slice(0,16).replace('T',' '):'No frames'} UTC</span><span>{frames.length} composites · last 24 hours</span></div>{error&&<span role="alert">{error}</span>}</section>
  </main>
}
