import React,{useEffect,useRef,useState} from 'react';
import {startGaiaGlobe} from './globe';
import './public-viewer.css';
import GaiaLogo from './GaiaLogo';
type LensModel={calibration_id:string;created_utc:string;valid_from_utc?:string|null;valid_to_utc?:string|null;method:string;residual_px?:number|null;format:string;sha256:string;url:string};
type CameraLens={source_id:string;name:string;producer:string;latitude_deg?:number|null;longitude_deg?:number|null;models:LensModel[]};
type Manifest={generated_utc:string;images:{at:string}[];credits:{name:string;website?:string;acknowledgement:string;copyright:string}[];lens_models?:CameraLens[]};
const date=(value?:string|null)=>value?new Date(value).toISOString().slice(0,10):'open';
export default function PublicViewer(){
  const canvas=useRef<HTMLCanvasElement>(null),epoch=useRef(Date.now()),loading=useRef(false);
  const [manifest,setManifest]=useState<Manifest>(),[index,setIndex]=useState(-1),[play,setPlay]=useState(false),[credits,setCredits]=useState(false),[error,setError]=useState('');
  useEffect(()=>{const controller=new AbortController();const refresh=()=>fetch('/gaia/public/manifest.json',{cache:'no-store',signal:controller.signal}).then(r=>{if(!r.ok)throw Error('Published images unavailable');return r.json()}).then(m=>{setManifest(m);setError('')}).catch(e=>{if(!controller.signal.aborted)setError(String(e.message))});void refresh();const timer=setInterval(refresh,60000);return()=>{controller.abort();clearInterval(timer)}},[]);
  useEffect(()=>canvas.current?startGaiaGlobe(canvas.current,()=>epoch.current,b=>{loading.current=b},true):undefined,[]);
  useEffect(()=>{if(manifest?.images.length)epoch.current=Date.parse(manifest.images[index<0?manifest.images.length-1:Math.min(index,manifest.images.length-1)].at)},[manifest,index]);
  useEffect(()=>{if(!play||!manifest?.images.length)return;const timer=setInterval(()=>{if(!loading.current)setIndex(i=>(i+1)%manifest.images.length)},250);return()=>clearInterval(timer)},[play,manifest]);
  const frames=manifest?.images||[],at=frames[index<0?frames.length-1:Math.min(index,frames.length-1)]?.at;
  return <main className="gaia-public">
    <header className="public-header"><div className="public-brand"><GaiaLogo/><div><h1>GAIA <span>Data Center</span></h1><p>Global Auroral Image Archive</p></div></div><a className="public-uit" href="https://uit.no/" target="_blank" rel="noreferrer"><img src="/gaia/uit-logo-white.png" alt="UiT The Arctic University of Norway"/></a><button aria-expanded={credits} onClick={()=>setCredits(!credits)}>ⓘ <span>Info &amp; credits</span></button></header>
    <div className="public-globe"><canvas ref={canvas} aria-label="Interactive auroral globe"/><div className="public-hint">Drag to rotate · Scroll or pinch to zoom</div>
    {credits&&<section className="public-info" role="dialog" aria-label="Information and credits"><div className="public-info-heading"><h2>About GAIA</h2><button onClick={()=>setCredits(false)} aria-label="Close information">✕</button></div><img src="/gaia/uit-logo-white.png" alt="UiT" width={120}/><p>Juha Vierinen · Björn Gustavsson</p><p>GAIA is a service that compiles images of the aurora from publicly available data sources.</p><p>GAIA was inspired in part by the <a href="https://data.phys.ucalgary.ca/" target="_blank" rel="noreferrer">University of Calgary THEMIS All-Sky Imager array</a>, whose continent-scale observations have been enormously influential in auroral research. GAIA is an independent project.</p><p>Drag to rotate the globe. Scroll or pinch to zoom. Press Play to explore recent auroral activity, or Latest to see the newest images.</p><h2>Camera lens models</h2><p>Downloadable calibrations are the exact AIDA/WISC HDF5 files used to place camera pixels on the globe. Azimuth is degrees clockwise from geographic north; elevation is degrees above the horizon. Image coordinates are zero-based raw pixel centres.</p><p>In Python, read <code>/wisc_optpar_with_optmod</code> and the root <code>image_width</code> and <code>image_height</code> attributes with <code>h5py</code>, then pass them with <code>(x, y)</code> to <a href="https://github.com/jvierine/widefield-star-calibrator/blob/main/wisc_lens.py" target="_blank" rel="noreferrer"><code>pixel_to_az_el</code></a>. For dated images, select the model whose half-open validity interval contains the observation time. Verify the downloaded file against its SHA-256 value.</p>{manifest?.lens_models?.map(camera=><details className="lens-camera" key={camera.source_id}><summary>{camera.name} <span>{camera.models.length} model{camera.models.length===1?'':'s'}</span></summary><p>{camera.producer}{camera.latitude_deg!=null&&camera.longitude_deg!=null?` · ${camera.latitude_deg.toFixed(3)}°, ${camera.longitude_deg.toFixed(3)}°`:''}</p><ul>{camera.models.map(model=><li key={model.calibration_id}><a href={model.url} download>{date(model.valid_from_utc)}–{date(model.valid_to_utc)} · Download HDF5</a>{model.residual_px!=null?` · ${model.residual_px.toFixed(3)} px RMS`:''}<br/><code>SHA-256 {model.sha256}</code></li>)}</ul></details>)}<h2>Data providers &amp; credits</h2><p>GAIA is made possible by the observatories and camera operators who share their images. All images remain the copyright of their respective producers.</p>{manifest?.credits.map((c,i)=><p key={i}><a href={c.website||undefined} target="_blank" rel="noreferrer">{c.name}</a><br/>{c.acknowledgement}<br/>{c.copyright}</p>)}</section>}</div>
    <section className="public-playback" aria-label="Aurora playback"><div className="public-playback-row"><button className="public-play" disabled={!frames.length} onClick={()=>{if(!play&&index<0)setIndex(0);setPlay(!play)}}>{play?'❚❚ Pause':'▶ Play'}</button><button disabled={!frames.length} onClick={()=>{setPlay(false);setIndex(-1)}}>Latest</button><time>{at?new Date(at).toISOString().replace('T',' ').replace('.000Z',' UTC'):'Waiting for publication'}</time></div><input aria-label="Observation time" disabled={!frames.length} type="range" min={0} max={Math.max(0,frames.length-1)} value={index<0?Math.max(0,frames.length-1):Math.min(index,frames.length-1)} onChange={e=>setIndex(Number(e.target.value))}/><div className="public-timeline-labels"><span>{frames.length?new Date(frames[0].at).toISOString().slice(0,16).replace('T',' '):'No frames'} UTC</span><span>{frames.length} composites · last 24 hours</span></div>{error&&<span role="alert">{error}</span>}</section>
  </main>
}
